# https://neptune.ai

neptune:
  _target_: lightning.pytorch.loggers.neptune.NeptuneLogger
  api_key: # api key is loaded from environment variable
  project: holvan/foundation-sdd
  tags: ${tags}
  name: ${task_name}
  log_model_checkpoints: False
  prefix: ""
