defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}-eer_{val/eer:.4f}"
  verbose: True
  monitor: "val/eer"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 3

early_stopping:
  monitor: "val/eer"
  patience: 10
  mode: "min"

model_summary:
  max_depth: -1
